export const about = {
    id: 'about',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Inicia tu viaje',
    headline: 'Experiencias únicas garantizadas',
    description: 'Descarga nuestra app y recibe notificaciones sobre los mejores descuentos para vos.',
    buttonLabel: 'Comenzar',
    imgStart: false,
    img: require('../../assets/images/mobile_app.svg').default,
    alt: 'Bussines_Woman',
    dark: false,
    primary: false,
    darkText: true
}
export const homeObjTwo = {
    id: 'discover',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Unlimited Access',
    headline: 'Login to your account at any time',
    description: 'We have you covered no matter where you are located. All you need is an internet connection and a phone or computer',
    buttonLabel: 'Learn More',
    imgStart: true,
    img: require('../../assets/images/data.svg').default,
    alt: 'Bussines_Woman',
    dark: false,
    primary: true,
    darkText: true
}
export const homeObjThree = {
    id: 'signup',
    lightBg: true,
    lightTextDesc: true,
    topLine: 'Join our Team',
    headline: 'Creating an account is extremely easy',
    lightText: false,
    description: 'Get everything set up and ready in under 10 minutes. All you need to do is add your information and you are ready to go',
    darkText: true,
    buttonLabel: 'Start Now',
    imgStart: true,
    img: require('../../assets/images/interview.svg').default,
    alt: 'Bussines_Woman',
    dark: false,
    primary: false,
}